mysite/urls.py
from django.contrib import admin, auth
from django.conf import settings
from django.contrib.auth.decorators import login_required
# admin.autodiscover()
from django.contrib import auth
from django.urls import path
from django.conf.urls import url
from django.urls.conf import re_path
import mysites.views
from mysites.line import callback
#path(pattern,action)
urlpatterns = [
    path('callback/', callback),
    path('admin/', admin.site.urls),
    url(r'^menu/$',mysites.views.menu),
    url(r'^welcome/$',mysites.views.welcome),
    re_path(r'comment/(?P<id>\d{1,5})/',login_required(mysites.views.comment)),
    path('accounts/login/',mysites.views.sign_in,name='Login'),
    path('accounts/register/',mysites.views.register, name='Register'),
    path('index/', mysites.views.IndexView.as_view()),
    path('', mysites.views.IndexView.as_view()),
    path('accounts/logout/',mysites.views.logout),
    path('firstmenu/', mysites.views.menu, {'id':'1'}),
    path('secondmenu/', mysites.views.menu, {'id':'2'}),
    path('restaurants_list/', mysites.views.list, {'model': mysites.models.Restaurant}),
    path('users_list/',mysites.views.list, {'model': auth.models.User}),
    path('index2/',mysites.views.index)
    
]
if settings.DEBUG:#DEBUG模式開啟後才能用的功能
    urlpatterns += [
        # url(r'^(\w+)/math/(\w+)/$',mysites.views.math), #(\w+))代表接收的參數
    ]

mysites/models.py
from django.db import models, connection

# Create your models here.
class Restaurant(models.Model):
    name=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=15)
    address=models.CharField(max_length=50,blank=True)
    def __unicode__(self):
        return self.name
    def __str__(self):
        return self.name
class SpicyFoodManager(models.Manager):
    def get_queryset(self):
        return super(SpicyFoodManager, self).get_queryset().filter(is_spicy=True)
    def cheap_food_num(self):
        return self.filter(price_lte=100).count()
    def get_120_food(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT name 
            FROM restaurants_food 
            WHERE price=120
        """)
        return [result[0] for result in cursor.fetchall()]
class Food(models.Model):
    name=models.CharField(max_length=20)
    price=models.DecimalField(max_digits=3,decimal_places=0)
    comment=models.CharField(max_length=50,blank=True)
    is_spicy=models.BooleanField(default=False)
    restaurant=models.ForeignKey(Restaurant,on_delete=models.SET)
    objects=SpicyFoodManager()
    def __unicode__(self):
        return self.name
    def __str__(self):
        return   self.name
    class Meta:
        ordering=['restaurant']

class Comment(models.Model):
    content=models.CharField(max_length=255)
    visitor=models.CharField(max_length=255)
    email=models.EmailField(max_length=255)
    date_time=models.DateTimeField()
    restaurant=models.ForeignKey(Restaurant,on_delete=models.SET)
    def __unicode__(self):
        return self.name
    def __str__(self):
        return   str(self.restaurant)+"  的評論"
    class Meta:
        ordering=['date_time']
        permissions=(
            ("can_comment","Can_comment"),

        )

class LineAccount(models.Model):
    u_id=models.CharField(max_length=255,primary_key=True)
    user_displayname=models.CharField(max_length=255)

class language(models.Model):
    request=models.CharField(max_length=100,primary_key=True)
    response=models.CharField(max_length=100)

class investigate(models.Model):
    User = models.CharField(max_length=255,primary_key=True)
    date = models.DateTimeField()
    program = models.CharField(max_length=50)

class image(models.Model):
    request = models.CharField(max_length=100, primary_key=True)
    response = models.CharField(max_length=100)

class AlbumModel(models.Model):
    adate=models.DateTimeField(auto_now=True)
    alocation=models.CharField(max_length=200,blank=True,default='')
    atitle=models.CharField(max_length=100,null=False)
    adesc=models.TextField(blank=True,default='')
    def __str__(self):
        return self.atitle

class PhotoModel(models.Model):
    palbum=models.ForeignKey('AlbumModel',on_delete=models.CASCADE)
    psubject=models.CharField(max_length=100,null=False)
    pdate=models.DateTimeField(auto_now=True)
    purl=models.CharField(max_length=100,null=False)
    phit=models.IntegerField(default=0)
    def __str__(self):
        return self.psubject

templates/albumphoto.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
  <div class="subjectDiv">標題 {{photo.palbum.atitle}}</div>
    <div class="actionDiv"><a href="/albumshow/{{album}}/">回上一頁</a></div>
    <div class="photoDiv"><img src="/media/{{photo.purl}}" /></div>
    <div class="normalDiv">
      <p align="center">{{photo.psubject}}</p>
    </div>
{% endblock %}

templates/albumshow.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
  <div class="subjectDiv"> 標題 {{monophoto.palbum.atitle}}</div>
    <div class="actionDiv">照片總數：{{totalphoto}} </div>
    <div class="normalDiv">
      <p><strong>拍攝時間</strong>：{{monophoto.palbum.adate}} 
        <strong>拍攝地點</strong>：{{monophoto.palbum.alocation}}</p>
      <p>{{monophoto.palbum.adesc}}</p>
    </div>
    {% for photo in photos %}
      <div class="albumDiv">
        <div class="picDiv"><a href="/albumphoto/{{photo.id}}/{{album}}/"><img src="/media/{{photo.purl}}" width="120" height="120" border="0" /></a></a></div>
        <div class="albuminfo"><a href="/albumphoto/{{photo.id}}/{{album}}/">{{photo.psubject}}</a><br />
          <span class="smalltext">點閱次數：</span>{{photo.phit}}</div>
      </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet2" href="css/base.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"> {% block css %}{% endblock css %}
</head>

<body>



    <nav class="navbar justify-content-start navbar-fixed-top"style="background-color:black;" role="navigation ">
        <div class="container ">
            <div class="navbar-header ">
                <button type="button " class="navbar-toggle collapsed " data-toggle="collapsed " data-target="#navbar " aria-expanded="false " aria-controls="#navbar ">

        <span class="sr-only ">Toggle navigation</span>
        <span class="icon-bar "></span><span class="icon-bar "></span><span class="icon-bar "></span>
    </button>
                <a class="navbar-brand " href="/index/" style="color: #76b852;">MySite</a>

            </div>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" href="/restaurants_list/" style="color: #76b852;">餐廳列表</a>
                </li>

                <li class="nav-item disable">{% if request.user.is_authenticated %}
                    <a class="nav-link active" href="/users_list/" style="color: #76b852;">您好 {{request.user}}!</a> {% else%}<a class="nav-link" href="#" style="color: #76b852;">Link</a> {%endif%}
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    <a class="nav-link " style="color: #76b852;" href="/accounts/logout/">登出</a>{% else%}
                    <a class="nav-link " style="color: #76b852;" href="/accounts/login/">登入</a>{%endif%}

                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock content %}
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</html>

templates/base2.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>網路相簿</title>
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>

<body bgcolor="#cccccc">
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/index/">
                <img src="{% static 'images/logo.png' %}" alt="" width="30" height="24" class="d-inline-block align-text-top"> Web Album
            </a>
            <form class="d-flex">
                <a class="btn btn-outline-secondary" href="/index/">[相簿首頁]</a>
                <a class="btn btn-outline-secondary" href="/login/">[相簿管理]</a>
            </form>
        </div>
    </nav>

    <table width="778" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
            <td height="124" valign="top" background="{% static 'images/album_r1_c1.jpg' %}">
                <!-- <div class="titleDiv"> [生活、旅行的記錄]<br /></div>
                <div class="menulink">
                    <a href="/index/">[相簿首頁]</a>
                    <a href="/login/">[相簿管理]</a>
                </div> -->
            </td>
        </tr>
        <tr>
            <td background="{% static 'images/album_r2_c1.jpg' %}">
                <div id="mainRegion">
                    <table width="90%" border="0" align="center" cellpadding="4" cellspacing="0">
                        <tr>
                            <td>
                                {% block content %}{% endblock %}
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr>
            <td align="center" background="{% static 'images/album_r2_c1.jpg' %}" class="trademark">fan9704 網站相簿&nbsp;版權所有 &copy; 2021&nbsp;fan9704 Album All Rights Reserved. </td>
        </tr>
        <tr>
            <td><img name="album_r4_c1" src="{% static 'images/album_r4_c1.jpg' %}" width="778" height="24" border="0" id="album_r4_c1" alt="" /></td>
        </tr>
    </table>
</body>

</html>

templates/comments.html
{% extends 'base.html' %}

    {% block title %}Document{% endblock title %}{% block css %}
    <style>
        
        form,
        p,
        h2 {
            align-items: center;
            text-align: center;
        }
        
        p,
        h2,
        td {

            margin: 0;
            padding: 15px;
        }
        

    </style>{% endblock css %}


{% block content %}
    <h2>{{r.name}}的評價</h2>
    {% if r.comment_set.all %}
    <p>目前共有{{r.comment_set.all|length}}條評價</p>
    <table class="table ">
        <tr>
            <th>留言者</th>
            <th>時間</th>
            <th>評價</th>
        </tr>
        {% for c in r.comment_set.all %}
        <tr>
            <td>{{c.visitor}}</td>
            <td>{{c.date_time}}</td>
            <td>{{c.content}}</td>
        </tr>
        {% endfor%}
    </table>
    {% else%}
    <p>無評價</p>
    {%endif %}

    <hr>
    <div class="col-12 table-responsive   container-fluid"> <br><br> {% if f.errors %}
        <p style="color: red;">請依提示修復表單</p>
        {%endif%}
        <form action="" method="POST">{% csrf_token %}
            <!-- <table class="table">{{f.as_table}}</table> -->

            <table class="table">
                <tr>
                    <th><label for="id_visitor">留言者:</label></th>
                    <td> {{f.visitor}}</td>
                    <td> {{f.visitor.errors}}</td>
                </tr>
                <tr>
                    <th><label for="id_email">電子信箱:</label></th>
                    <td> {{f.email}}</td>
                    <td> {{f.email.errors}}</td>
                </tr>
                <tr>
                    <th><label for="id_content">評價:</label></th>
                    <td> {{f.content}}</td>
                    <td> {{f.content.errors}}</td>
                </tr>

            </table>
            <input type="submit" value="給予評價">


        </form>
    </div>
{% endblock content %}
   

templates/index.html
{% extends 'base.html' %}
{% block title %}Restaurant King{% endblock title %} 
{% block css %}
    <style>
        h2 {
            text-align: center;
            line-height: 2;
            padding: 10px;
            margin-top: 20px;
        }
        
        .user {
            text-align: center;
            align-items: center;
        }
        
        a.user {
            width: 100%;
            position: absolute;
        }

</style>{% endblock css %}
{% block content %}
    <h2>歡迎來到餐廳王</h2>
    {% if request.user.is_authenticated %}
    <p class="user">{{request.user}}你已經登入囉~
        <a href="/accounts/logout/">登出</a>
    </p>
    <a class="user" href="/restaurants_list/">餐廳列表</a> {% else%}
    <p class="user">您尚未登入喔~ <a href="/accounts/login/">登入</a></p>
    {%endif%}
{% endblock content %}
    

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:300);
        .login-page {
            width: 360px;
            padding: 8% 0 0;
            margin: auto;
        }
        
        .form {
            position: relative;
            z-index: 1;
            background: #FFFFFF;
            max-width: 360px;
            margin: 0 auto 100px;
            padding: 45px;
            text-align: center;
            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
        }
        
        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }
        
        .input {
            background: #4CAF50;
        }
        
        .form button,
        button input {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #4CAF50;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }
        
        .form button:hover,
        .form button:active,
        .form button:focus {
            background: #43A047;
        }
        
        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }
        
        .form .message a {
            color: #4CAF50;
            text-decoration: none;
        }
        
        .form .register-form {
            display: none;
        }
        
        .container {
            position: relative;
            z-index: 1;
            max-width: 300px;
            margin: 0 auto;
        }
        
        .container:before,
        .container:after {
            content: "";
            display: block;
            clear: both;
        }
        
        .container .info {
            margin: 50px auto;
            text-align: center;
        }
        
        .container .info h1 {
            margin: 0 0 15px;
            padding: 0;
            font-size: 36px;
            font-weight: 300;
            color: #1a1a1a;
        }
        
        .container .info span {
            color: #4d4d4d;
            font-size: 12px;
        }
        
        .container .info span a {
            color: #000000;
            text-decoration: none;
        }
        
        .container .info span .fa {
            color: #EF3B3A;
        }
        
        body {
            background: #76b852;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(right, #76b852, #8DC26F);
            background: -moz-linear-gradient(right, #76b852, #8DC26F);
            background: -o-linear-gradient(right, #76b852, #8DC26F);
            background: linear-gradient(to left, #76b852, #8DC26F);
            font-family: "Roboto", sans-serif;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
        
        h2 {
            color: #76b852;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
    <div class="login-page">
        <div class="form">
            <h2>登入</h2>
            <form class="login-form" action="" method="POST">{% csrf_token%}
                <table> {{form.as_table}}</table>
                <button type="submit" value="login" class="input"> login</button>
                <p class="message">Not registered? <a href="/accounts/register/">Create an account</a></p>
            </form>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        $('.message a').click(function() {
            $('form').animate({
                height: "toggle",
                opacity: "toggle"
            }, "slow");
        });
    </script>
</body>

</html>

templates/menu.html
{% extends 'base.html' %}
{% load myfliters %}
{% block title %}Menu{% endblock title %}
   {% block css %}
    <style>
        th,
        p,
        h2,
        td {
            text-align: center;
        }
        
        div.menus {
            text-align: center;
            padding: 40px 15px;
        }
    </style>{% endblock css %}


<body>
{% block content %}


    <h2>{{restaurants.name}}的menu</h2>
    {% if restaurants.food_set.all %}
    <p>本餐廳共有{{ restaurants.food_set.all|length }}道菜</p>
    <table class="table">
        <tr>
            <th>菜名</th>
            <th>價格</th>
            <th>甜不辣</th>
            <th>註解</th>
        </tr>
        {% for food in restaurants.food_set.all%}
        <tr>
            <td>{{food.name}}</td>
            <td>{{food.price}}</td>
            <td>{{food.is_spicy|yes_no:"辣/不辣" }}</td>
            <td>{{food.comment}}</td>
        </tr>
        {%endfor%}
    </table>

    {% else %}
    <p>本餐廳啥都沒賣</p>
    {% endif%}

{% endblock  %} 
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivrestaurants.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js " integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF " crossorigin="anonymous "></script>

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:300);
        .login-page {
            width: 540px;
            padding: 8% 0 0;
            margin: auto;
        }
        
        .form {
            position: relative;
            z-index: 1;
            background: #FFFFFF;
            max-width: 480px;
            margin: 0 auto 100px;
            padding: 45px;
            text-align: center;
            box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
        }
        
        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }
        
        .input {
            background: #4CAF50;
        }
        
        .form button,
        button input {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #4CAF50;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }
        
        .form button:hover,
        .form button:active,
        .form button:focus {
            background: #43A047;
        }
        
        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }
        
        .form .message a {
            color: #4CAF50;
            text-decoration: none;
        }
        
        .container {
            position: relative;
            z-index: 1;
            max-width: 300px;
            margin: 0 auto;
        }
        
        .container:before,
        .container:after {
            content: "";
            display: block;
            clear: both;
        }
        
        .container .info {
            margin: 50px auto;
            text-align: center;
        }
        
        .container .info h1 {
            margin: 0 0 15px;
            padding: 0;
            font-size: 36px;
            font-weight: 300;
            color: #1a1a1a;
        }
        
        .container .info span {
            color: #4d4d4d;
            font-size: 12px;
        }
        
        .container .info span a {
            color: #000000;
            text-decoration: none;
        }
        
        .container .info span .fa {
            color: #EF3B3A;
        }
        
        body {
            background: #76b852;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(right, #76b852, #8DC26F);
            background: -moz-linear-gradient(right, #76b852, #8DC26F);
            background: -o-linear-gradient(right, #76b852, #8DC26F);
            background: linear-gradient(to left, #76b852, #8DC26F);
            font-family: "Roboto", sans-serif;
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
        }
        
        h2 {
            color: #76b852;
        }
        .error{
            display:none;
            color:red;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>

    <div class="login-page">
        <div class="form">
            <h2>註冊</h2>
            <form class="register-form" action="" method="POST">
                <p class="error">密碼確認不一致或者密碼與帳號相似</p>
                <table>{{ form.as_p }}</table>

                <button type="submit" value="login" class="input">create</button>{% csrf_token%}
                <p class="message">Already registered? <a href="/accounts/login/">Sign In</a></p>
            </form>

        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        $('.message a').click(function() {
            $('form').animate({
                height: "toggle",
                opacity: "toggle"
            }, "slow");
        });
        $('button.input').click(()=>{
            $('.error').animate({
                 height: "show",
                opacity: "show"
            }, "slow");
        })
    </script>
</body>

</html>

templates/restaurants_list.html
{% extends 'base.html' %} {% block title %}Menu Document{% endblock title %} {% block css %}
<style>
    h2,
    form {
        text-align: center;
        color: rgb(6, 158, 82);
    }
    
    .row {
        background-color: #76b852;
        padding: 10px;
    }
    
    .row .col-12 {
        background-color: #000;
    }
    
    .table th {
        color: #72d83b;
    }
    
    .table td {
        color: white;
        line-height: 2;
    }
    
    button,
    td a {
        border-radius: 5px;
        padding: 5px;
        background-color: #76b852;
        color: black;
        font-weight: bold;
        border: solid black 2px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
</style>{% endblock css %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h2 style="margin: 10px auto;">餐廳列表</h2>
            <form action="/menu/" method="GET">
                <table class="table">
                    <tr>
                        <th>選取</th>
                        <th>店名</th>
                        <th>電話</th>
                        <th>地址</th>
                        {% if perms.restaurants.can_comment %}
                        <th>評價</th>
                        {% endif %}
                    </tr>
                    {% for r in objs %}
                    <tr>
                        <td><a href="/menu/?id={{r.id}}">看菜單</a></td>
                        <td>{{r.name}}</td>
                        <td>{{r.phone_number}}</td>
                        <td>{{r.address}}</td>
                        <td><a href="/comment/{{r.id}}/">評論</a></td>
                    </tr>
                    {% endfor%}
                </table>
                <!-- <input type="submit" value="觀看menu" style="margin-bottom: 10px;"> -->
        </div>
    </div>
    </form>

</div>
{%endblock %}

templates/users_list.html
{% extends 'base.html' %} {% block title %}User_list{% endblock title %} {% block css %}
<style>
    .row {
        background-color: #76b852;
        padding: 10px;
    }
    
    .row .col-12 {
        background-color: #000;
    }
    
    .table th {
        color: #72d83b;
    }
    
    .table td {
        color: white;
    }
</style>{% endblock css %} {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <table class="table">
                <tr>
                    <th>使用者帳號</th>
                    <th>使用者姓名</th>
                </tr>
                {% for u in objs %}
                <tr>
                    <td>{{u.username}}</td>
                    <td>{{u.last_name}} {{u.first_name}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="/welcome/" method="GET">
        <label for="user_name">您的名字</label>
        <input id="user_name" type="text" name="user_name">
        <input type="submit" value="進入網站">
    </form>
</body>

</html>